version: "3.7"

services:
  halloid-aurelia-mdc-template:
    image: halloid-aurelia-mdc-template:0.1.0
    build:
      context: . # relative to docker-compose.yml
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    restart: unless-stopped
